### ISSUE TITLE
Tiller process crash when running helm list on objects that no longer exist in k8s

### ISSUE THREAD

**Issue by lachie83** [kubernetes/helm#1083]
```
helm list
2016/08/19 16:03:06 transport: http2Client.notifyError got notified that the client transport was broken EOF.
Error: transport is closing
```

```
k get deployments,pods,svc --namespace=kube-system | grep tiller
tiller-deploy-610593871-xq3bk                        0/1            Error         2                   40m
```

```
k logs tiller-deploy-610593871-xq3bk --previous  --namespace=kube-system
Tiller is running on :44134
Tiller probes server is running on :44135
Storage driver is ConfigMap
2016-08-19 23:03:05.799271 I | Listing all deployed releases in storage
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x576ec9]

goroutine 56 [running]:
panic(0x14729c0, 0xc42000a030)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
k8s.io/helm/pkg/storage.StatusFilter.func1(0xc420340f50, 0xc42027d550)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/storage/filter.go:65 +0x19
k8s.io/helm/pkg/storage.FilterFunc.Check(0xc42027d550, 0xc420340f50, 0xc420340f50)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/storage/filter.go:30 +0x35
k8s.io/helm/pkg/storage.(*Storage).ListDeployed.func1(0xc420340f50, 0x0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/storage/storage.go:84 +0x41
k8s.io/helm/pkg/storage/driver.(*ConfigMaps).List(0xc42027cc20, 0x16c15f0, 0x1, 0x13d1d60, 0xc420324320, 0x2fa39abd, 0x1ec1f80)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/storage/driver/cfgmaps.go:108 +0x282
k8s.io/helm/pkg/storage.(*Storage).ListDeployed(0xc42027cc30, 0x7f784c6944b0, 0x0, 0x2, 0xc420076578, 0x16bdff2)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/storage/storage.go:85 +0xc1
main.(*releaseServer).ListReleases(0xc420022258, 0xc4202b8400, 0x1e940a0, 0xc420324310, 0x0, 0xc420295cd0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/cmd/tiller/release_server.go:64 +0x4a
k8s.io/helm/pkg/proto/hapi/services._ReleaseService_ListReleases_Handler(0x1588420, 0xc420022258, 0x1e927e0, 0xc420076500, 0x0, 0xc4201ce800)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/proto/hapi/services/tiller.pb.go:518 +0x117
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).processStreamingRPC(0xc420076c00, 0x1e941c0, 0xc420088120, 0xc4200802a0, 0xc420474680, 0x1eaf6c0, 0xc4203528a0, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:575 +0x22a
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).handleStream(0xc420076c00, 0x1e941c0, 0xc420088120, 0xc4200802a0, 0xc4203528a0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:650 +0xc33
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4204681b0, 0xc420076c00, 0x1e941c0, 0xc420088120, 0xc4200802a0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:323 +0xab
created by k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:324 +0xa3
```

```
k get configmap ardent-otter --namespace=kube-system
NAME           DATA      AGE
ardent-otter   1         49m
k get configmap ardent-otter --namespace=kube-system -o yaml
apiVersion: v1
data:
  release: <snip>
kind: ConfigMap
metadata:
  creationTimestamp: 2016-08-19T22:11:21Z
  labels:
    CREATED_AT: "1471644681"
    NAME: ardent-otter
    OWNER: TILLER
    STATUS: DEPLOYED
    VERSION: "1"
  name: ardent-otter
  namespace: kube-system
  resourceVersion: "100128"
  selfLink: /api/v1/namespaces/kube-system/configmaps/ardent-otter
  uid: dc28c0fa-6659-11e6-9465-42010a800005
```

```
helm version
v2.0.0-alpha.3
```

**Comment by technosophos** [comment]
Ewww.

What do you mean "objects that no longer exist"? Was a ConfigMap manually deleted or something?

We'll definitely hunt this one down.

**Comment by lachie83** [comment]
So in this specific case this is what happened


I have a `trunc 24` on the Name which sometimes lands it on a hyphen. I think theres an issue on this already open. Need to dig
```
helm install charts/spark/ --namespace=spark
Error: release tufted-garfish failed: [Service "tufted-garfish-zeppelin-" is invalid: metadata.name: Invalid value: "tufted-garfish-zeppelin-": must match the regex [a-z]([-a-z0-9]*[a-z0-9])? (e.g. 'my-name' or 'abc-123'), Deployment.extensions "tufted-garfish-zeppelin-" is invalid: [metadata.name: Invalid value: "tufted-garfish-zeppelin-": must match the regex [a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)* (e.g. 'example.com'), spec.template.spec.containers[0].name: Invalid value: "tufted-garfish-zeppelin-": must match the regex [a-z0-9]([-a-z0-9]*[a-z0-9])? (e.g. 'my-name' or '123-abc')]]
```

Even though I get an error here it still lays down the resources. I was nuking them manually but missed cleaning up the configMap.

Something like
`k delete deployments,svc -l release=tufted-garfish --all --namespace=spark
`

Once I found that the configMap was still laying around. Thanks Jason H! I could simply nuke it and problem solved. We should simply handle this error I guess.

**Comment by technosophos** [comment]
Nah, you shouldn't ever manually nuke the configmap. That is the one condition that I can imagine actually causing the panic (though it should be an error, not a panic).

Simply deleting the resources shouldn't cause a nil pointer, or even an error on a list command. So something in there didn't get handled correctly.

**Comment by lachie83** [comment]
LMK if you need any further detail.

**Comment by lachie83** [comment]
Thanks for the quick response!

**Comment by technosophos** [comment]
Ah! The error indicates that there's something corrupt in the snipped out section of the configmap. I found where it's happening. The status field is missing in the base64-encoded data. I'll hunt that down on Monday.

The good news, though, is that it has nothing to do with your deleting things out of Kubernetes. THere's just a bit of code somewhere that is not setting the right status.

**Comment by lachie83** [comment]
I still have the snip b64 payload. Would it help to attach it?

**Comment by devth** [comment]
I'm hitting this too. What's the best way to recover? Can I delete the `data` key/val from the configmap?

**Comment by adamreese** [comment]
This issue is cause by `helm init` installing an unversioned tiller image.  It has been fixed in #1118 

If you need a work around you can install the correct image by running init with the correct version.

`helm init --image gcr.io/kubernetes-helm/tiller:v2.0.0-alpha.3`

**Comment by danny-waite** [comment]
appears to be still not working for me, I did:

kubectl --namespace kube-system delete pod tiller-deploy-610593871-gkeai
helm init -i gcr.io/kubernetes-helm/tiller:v2.0.0-alpha.3
helm list

and got: 
```
transport: http2Client.notifyError got notified that the client transport was broken EOF.
Error: transport is closing
```

**Comment by danny-waite** [comment]
my mistake, should have been deleting the deployment and not the pod

`kubectl --namespace kube-system delete deployment tiller-deploy`
