### ISSUE TITLE
"Error: context deadline exceeded" on GKE

### ISSUE THREAD

**Issue by dictcp** [kubernetes/helm#2409]
I tried to install latest Helm (v2.4.1) on my fresh created GKE cluster (with k8s 1.5.7). and it give out error whenever I install any chart. Attached are the logging of my previous command execution.

```
~ gcloud container clusters get-credentials minidock --zone xxxxxx --project xxxxxx
Fetching cluster endpoint and auth data.
kubeconfig entry generated for minidock.
~ helm init
$HELM_HOME has been configured at /home/dick/.helm.

Tiller (the helm server side component) has been installed into your Kubernetes Cluster.
Happy Helming!
~ kubectl get po --namespace kube-system
NAME                                                            READY     STATUS    RESTARTS   AGE
fluentd-cloud-logging-gke-minidock-default-pool-9b0813ac-3zdz   1/1       Running   0          21m
heapster-v1.2.0.1-1244163626-jmtpv                              2/2       Running   0          21m
kube-dns-3475745875-ngw5q                                       4/4       Running   0          22m
kube-dns-autoscaler-2835134359-1z3hg                            1/1       Running   0          22m
kube-proxy-gke-minidock-default-pool-9b0813ac-3zdz              1/1       Running   0          22m
kubernetes-dashboard-3968242289-t3gpk                           1/1       Running   0          22m
l7-default-backend-2001230086-vt3n0                             1/1       Running   0          22m
tiller-deploy-3210876050-4p7sx                                  1/1       Running   0          20m
~ kubectl --namespace kube-system logs tiller-deploy-3210876050-4p7sx 
Starting Tiller v2.4.1 (tls=false)
GRPC listening on :44134
Probes listening on :44135
Storage driver is ConfigMap
~ helm install --debug stable/wordpress 
[debug] Created tunnel using local port: '34772'

[debug] SERVER: "localhost:34772"

[debug] Fetched stable/wordpress to wordpress-0.6.0.tgz

[debug] CHART PATH: /home/dick/wordpress-0.6.0.tgz

Error: context deadline exceeded
```

**Comment by thomastaylor312** [comment]
Could you get us the tiller logs for when this happened?

**Comment by munnerz** [comment]
I'm also seeing exactly the same issue -

no logs at all from tiller, except the standard start up logs:

```
Starting Tiller v2.4.2 (tls=false)
GRPC listening on :44134
Probes listening on :44135
Storage driver is ConfigMap
```

I'm also seeing this with Tiller v2.4.2 with Helm v2.4.2. Let me know if there's any other info you need...

**Comment by munnerz** [comment]
Full logs attached - note: I'm running 1.6.2 not 1.5.x here and getting the same issue. Issue also occurs with Tiller 2.4.2 with Helm 2.3.1.

<details>
bash-4.3# kubectl get no
NAME                                            STATUS    AGE       VERSION
gke-gs-staging-gke-default-pool-8a9f998e-ghwc   Ready     2d        v1.6.2
bash-4.3# kubectl get po -n kube-system
NAME                                                       READY     STATUS    RESTARTS   AGE
fluentd-gcp-v2.0-j2xff                                     1/1       Running   0          2d
heapster-v1.3.0-3440173064-bz5jr                           2/2       Running   0          2d
kube-dns-3263495268-0hn0m                                  3/3       Running   0          2d
kube-dns-autoscaler-2362253537-dv7d7                       1/1       Running   0          2d
kube-proxy-gke-gs-staging-gke-default-pool-8a9f998e-ghwc   1/1       Running   0          2d
kubernetes-dashboard-490794276-9ddww                       1/1       Running   0          2d
l7-default-backend-3574702981-dhj0x                        1/1       Running   0          2d
tiller-deploy-1651596238-v57zs                             1/1       Running   0          9m
bash-4.3# kubectl logs -n kube-system tiller-deploy-1651596238-v57zs
Starting Tiller v2.4.2 (tls=false)
GRPC listening on :44134
Probes listening on :44135
Storage driver is ConfigMap
bash-4.3# helm version --debug
[debug] Created tunnel using local port: '36495'

[debug] SERVER: "localhost:36495"

Client: &version.Version{SemVer:"v2.4.2", GitCommit:"82d8e9498d96535cc6787a6a9194a76161d29b4c", GitTreeState:"clean"}
[debug] context deadline exceeded
Error: cannot connect to Tiller
bash-4.3# kubectl logs -n kube-system tiller-deploy-1651596238-v57zs
Starting Tiller v2.4.2 (tls=false)
GRPC listening on :44134
Probes listening on :44135
Storage driver is ConfigMap
</details>

**Comment by munnerz** [comment]
I'm actually seeing this with all clusters, not just GKE.

I've also noticed Helm works fine from my OS X box to the same cluster. It seems to not work when in an alpine docker container. If I try the same process with a Debian container, it seems to work fine. The dockerfile in question that produces a Helm that doesn't work:

```
FROM alpine:3.5

RUN apk add --no-cache \
        openssl \
        curl \
        bash \
        python2 \
        make \
        graphviz \
        jq \
        ttf-ubuntu-font-family

# Install gcloud SDK
ENV GCLOUD_VERSION 153.0.0
ENV GCLOUD_HASH ade29e765f7847bf6081affb6eada69b45138d4abb443b1484e891312990e958
RUN cd /tmp && \
    curl -L https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${GCLOUD_VERSION}-linux-x86_64.tar.gz > /tmp/gcloud.tar.gz && \
    echo "${GCLOUD_HASH}  /tmp/gcloud.tar.gz" | sha256sum -c && \
    tar xvf /tmp/gcloud.tar.gz && \
    /tmp/google-cloud-sdk/install.sh && \
    rm -v /tmp/gcloud*

# Add gcloud binaries to PATH
ENV PATH /tmp/google-cloud-sdk/bin:$PATH

RUN gcloud components install -q kubectl

# Install terraform
ENV TERRAFORM_VERSION 0.9.4
ENV TERRAFORM_HASH cc1cffee3b82820b7f049bb290b841762ee920aef3cf4d95382cc7ea01135707
RUN cd /tmp && \
    curl -L https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip > /tmp/terraform.zip && \
    echo "${TERRAFORM_HASH}  /tmp/terraform.zip" | sha256sum -c && \
    unzip /tmp/terraform.zip && \
    mv terraform /usr/local/bin && \
    rm -v /tmp/terraform*

# Install helm
ENV HELM_VERSION v2.4.1
RUN cd /tmp && \
    curl -L https://storage.googleapis.com/kubernetes-helm/helm-${HELM_VERSION}-linux-amd64.tar.gz > /tmp/helm.tar.gz && \
    tar xvf /tmp/helm.tar.gz && \
    mv linux-amd64/helm /usr/local/bin && \
    rm -rf /tmp/linux-amd64*

ENV HOME /root
# copy contents of the git
WORKDIR /terraform
ADD . /terraform
```

Can anyone else replicate this using the above image? The tiller server itself is not receiving any requests at all, however the local port does seem to be forwarded fine as I'm able to make a request using `curl` (to be presented with unreadable characters, presumably because curl isn't speaking gRPC).

**Comment by thomastaylor312** [comment]
@munnerz I am seeing a [few](https://github.com/kubernetes/kubernetes/issues/27388) [related](https://github.com/kubernetes/kubernetes/issues/39028) [issues](https://github.com/kubernetes/kubernetes/issues/42164) in Kubernetes that appears to be related to Docker, possibly due to the number of pods running.

**Comment by munnerz** [comment]
In this case, one is a brand new 4 node GKE cluster (n1-standard-1) and
another single node bare metal cluster with about 40 pods (where tiller is
running).

Tiller itself isn't receive a request at all when helm is run in an alpine
container, but works fine on macOS and within a debian container.

Those issues appear unrelated except for the reference to "context deadline
exceeded", which is a common error message in Go coming from the context
package https://godoc.org/context#DeadlineExceeded

**Comment by thomastaylor312** [comment]
Ok, I'll dig in to this bug next after I finish the one I am working on

**Comment by thomastaylor312** [comment]
@munnerz I tried this with a non-GKE k8s and didn't have a problem. I don't have a GKE cluster to test against right now though

**Comment by h0tbird** [comment]
Same error here on GKE:
```
[0] ~ >> helm version
Client: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
[0] ~ >> helm list thevotingapp
NAME        	REVISION	UPDATED                 	STATUS  	CHART             	NAMESPACE   
thevotingapp	6       	Wed Jun 28 12:38:44 2017	DEPLOYED	thevotingapp-0.1.0	thevotingapp
[0] ~ >> helm get values thevotingapp
Error: context deadline exceeded
```

**Comment by bacongobbler** [comment]
I'm seeing the same issue on Azure. `helm list` and `helm get` work just fine, but I hit the context deadline as soon as I try `helm get manifest/values`.

output:

```
><> helm list
NAME       	REVISION	UPDATED                 	STATUS  	CHART              	NAMESPACE  
draft      	2       	Fri Jul  7 09:27:58 2017	FAILED  	draftd-canary      	kube-system
ingressctl 	1       	Thu Jul  6 15:16:48 2017	DEPLOYED	nginx-ingress-0.6.0	kube-system
><> helm get draft
REVISION: 2
RELEASED: Fri Jul  7 09:27:58 2017
CHART: draftd-canary
[...]
><> helm get manifest draft
Error: context deadline exceeded
```

No tiller logs were available after the call to `helm get manifest`, but `helm list` and `helm get` shows regular logs:

```
[storage] 2017/07/07 18:46:54 listing all releases with filter
[storage] 2017/07/07 18:47:07 getting last revision of "draft"
[storage] 2017/07/07 18:47:07 getting release history for "draft"
```

This is just on a 2-node cluster (one master, one node). I'll see if restarting the docker daemon on the node or just nuking the node from orbit will fix this issue.

**Comment by wangweihong** [comment]
I met this error in my cluster too, non-GKE. 
This is my Environment:

Host: 
```
   Linux node01 4.4.0-81-generic #104-Ubuntu SMP Wed Jun 14 08:17:06 UTC 2017 x86_64 x86_64 
x86_64 GNU/Linux
```
docker Version:
 ```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false

```
Error:
```
root@node01:~# helm version --debug
[debug] SERVER: "localhost:44134"

Client: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
[debug] context deadline exceeded
Error: cannot connect to Tiller
```
K8s Env:
```
root@node01:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.0", GitCommit:"58b7c16a52c03e4a849874602be42ee71afdcab1", GitTreeState:"clean", BuildDate:"2016-12-12T23:35:54Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:52:01Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by blackstar257** [comment]
Same!
`-> % helm get values excited-bison -a
Error: context deadline exceeded`

**Comment by tavispaquette** [comment]
Encountering the same problems on AWS with a kops-1.6.2 install using RBACs
helm get works, can install charts, but get manifest doesn't work

```
$ helm version --debug
[debug] Created tunnel using local port: '1474'

[debug] SERVER: "localhost:1474"

Client: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
```



```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.7", GitCommit:"095136c3078ccf887b9034b7ce598a0a1faff769", GitTreeState:"clean", BuildDate:"2017-07-05T16:40:42Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```



```
$ helm get manifest dunking-echidna
Error: context deadline exceeded
```

**Comment by bacongobbler** [comment]
This issue was fixed in https://github.com/kubernetes/helm/pull/2664 and is being shipped in v2.5.1.

**Comment by philchristensen** [comment]
I'm still having this issue even when using the latest canary release, which also seems to have some argument parsing errors.

Here's my kubectl output
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.7+coreos.0", GitCommit:"c8c505ee26ac3ab4d1dff506c46bc5538bc66733", GitTreeState:"clean", BuildDate:"2017-07-06T17:38:33Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```

Helm output from latest canary release:
```
$ helm version --debug
unknown flag: --debug
Usage of homer:
      --home string   location of your Helm config. Overrides $HELM_HOME (default "$HOME/.helm")
Client: &version.Version{SemVer:"v2.5+unreleased", GitCommit:"1261f71faf1aa8b9a127a6e1759fd799a51d9528", GitTreeState:"clean"}
[debug] context deadline exceeded
Error: cannot connect to Tiller
```

**Comment by bacongobbler** [comment]
Can you open a new issue for that, please?

You might also want to test https://github.com/kubernetes/helm/pull/2682. It sounds like this issue's already being fixed for v2.5.1.

**Comment by bacongobbler** [comment]
this issue was fixed in v2.5.1. Closing!

**Comment by roshangn88** [comment]
I can confirm that this is an issue in helm 2.5.0
```
$ helm list --kube-context xyz.k8s.domain.net --host domain-helm-charts.s3-website-eu-west-1.amazonaws.com --all
Error: context deadline exceeded
```

Looks like we need to upgrade

**Comment by roshangn88** [comment]
I can reproduce this with 2.5.1 too :(

**Comment by philchristensen** [comment]
The issues I had above were caused by not having registered the node names in local DNS. The fix was to add `--kubelet-preferred-address-types=InternalIP` to the apiserver manifest.

**Comment by YangYongZhi** [comment]
I can confirm that this is a issue in helm 2.6.0
[root@k8s-master ~]# helm install -f config.yaml stable/redis --tiller-namespace default --host 192.168.8.33:44134   --debug 
[debug] SERVER: "192.168.8.33:44134"

[debug] Original chart version: ""
[debug] Fetched stable/redis to /root/.helm/cache/archive/redis-0.9.0.tgz

[debug] CHART PATH: /root/.helm/cache/archive/redis-0.9.0.tgz

Error: context deadline exceeded


k8s version is :   
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:48:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:30:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by srossross** [comment]
Still an issue for me in 2.6.1 as well.

**Comment by gowthamsadasivam** [comment]
I'm also having this problem. I have a bare-metal three (1 master + 2 minions) nodes Kubernetes cluster up and running on Cent OS 7.

**Kubernetes Version**: `v1.5.2`

**Kubernetes Config** :
> `# kubectl config view`
> apiVersion: v1
> clusters: []
> contexts: []
> current-context: ""
> kind: Config
> preferences: {}
> users: []

**Kubernetes Cluster Info** :
> `# kubectl cluster-info`
> Kubernetes master is running at http://localhost:8080
> KubeDNS is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/kube-dns
> kubernetes-dashboard is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard


I've just followed the Helm installation steps from the documentation. After downloading the "helm" binary to the system path I did : `# helm init` 

> `Creating /root/.helm `
> `Creating /root/.helm/repository `
> `Creating /root/.helm/repository/cache `
> `Creating /root/.helm/repository/local `
> `Creating /root/.helm/plugins `
> `Creating /root/.helm/starters `
> `Creating /root/.helm/cache/archive `
> `Creating /root/.helm/repository/repositories.yaml `
> `$HELM_HOME has been configured at /root/.helm.`
> `Happy Helming!`


I can see `Tiller` pod is running : `# kubectl get pods -o wide --all-namespaces`

```
NAMESPACE     NAME                                    READY     STATUS    RESTARTS   AGE       IP            NODE
default       nginx-ingress-rc-s83kb                  1/1       Running   0          6d        172.30.71.3   minion03
kube-system   kube-dns-v20-z8lnd                      3/3       Running   0          21d       172.30.71.2   minion03
kube-system   kubernetes-dashboard-3543765157-tmmb8   1/1       Running   1          21d       172.30.89.2   minion02
kube-system   tiller-deploy-833363792-5v0gk           1/1       Running   0          10m       172.30.71.6   minion03
```

But, when I issue the version command : `helm version --debug`

> `Client: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}`
> `[debug] context deadline exceeded`
> `Error: cannot connect to Tiller`

^ Couldn't connect to `helm server` pod.

**Comment by worldfirst1** [comment]
Hi All, I am facing this issue on v2.6.2 and I am running my local kubernetes using minikube.

Has anyone been able to resolve this error ?

**Comment by grebois** [comment]
+1

**Comment by bacongobbler** [comment]
From looking at [kubernetes' issue queue](https://github.com/kubernetes/kubernetes/search?q=context+deadline+exceeded&type=Issues&utf8=%E2%9C%93), one possible reason why this error comes up is due to a bug with the docker daemon running on the node hosting tiller.

It might be good to see the docker daemon logs from the host running tiller, if anyone has those available.

**Comment by onlydole** [comment]
Is anyone experiencing this error after installing Helm with HomeBrew? I'm seeing success when installing directly with the "From Script" method in the wiki.

**Comment by bacongobbler** [comment]
FYI @onlydole I made a comment above that might help give you more insight into the error.

I don't think the difference between the CLI installed with homebrew and with the install script method will matter too much but it's definitely an interesting data point since homebrew [builds from source](https://github.com/cblecker/homebrew-core/blob/0f403053c61e6e5d404ba4fa16a165c8cc6deb14/Formula/kubernetes-helm.rb#L30-L39) whereas the install script uses the [pre-built binary](https://github.com/kubernetes/helm/blob/c5c6e6375b5e9f475bd65309f74af89e430db6b9/scripts/get#L79) CircleCI releases every tag.

If anyone is able to check and verify if homebrew vs. install script makes any difference, that would be helpful to know!

**Comment by veeresh1982** [comment]
I get this error too. My configuration is below

K8s version: 1.7.7

# helm version --host 10.245.112.10 --debug
[debug] SERVER: "10.245.112.10"

Client: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
[debug] context deadline exceeded
Error: cannot connect to Tiller

**Comment by bacongobbler** [comment]
@veeresh1982 can you check the tiller pod’s status using kubectl?

**Comment by onlydole** [comment]
@veeresh1982 - If you installed via Homebrew, can you try deleting and installing directly like this? https://github.com/kubernetes/helm/blob/master/docs/install.md#from-script 

Curious to see if that binary is the issue.

**Comment by veeresh1982** [comment]
Ok I did below to resolve : I am going to try @philchristensen solution too and update.
=======================================================
PREP on all master nodes: 
-----------------------------
On all master nodes following link: https://github.com/kubernetes/helm/issues/1455, updated /etc/hosts
10.245.112.12   cbu-dev-k8s-node0
10.245.112.11   cbu-dev-k8s-node1 
10.245.112.13   cbu-dev-k8s-node2

A) On each master nodes: try below
cbu-dev-k8s-master0 core # ./helm ls
NAME            REVISION        UPDATED                         STATUS          CHART                   NAMESPACE
knobby-donkey   1               Mon Nov 13 21:12:42 2017        DEPLOYED        hello-world-1.0.0       kube-system

cbu-dev-k8s-master1 core # ./helm ls
NAME            REVISION        UPDATED                         STATUS          CHART                   NAMESPACE
knobby-donkey   1               Mon Nov 13 21:12:42 2017        DEPLOYED        hello-world-1.0.0       kube-system


cbu-dev-k8s-master2 core # ./helm ls
NAME            REVISION        UPDATED                         STATUS          CHART                   NAMESPACE
knobby-donkey   1               Mon Nov 13 21:12:42 2017        DEPLOYED        hello-world-1.0.0       kube-system


B)From my another remote ubuntu machine:10.67.141.140 
1)
Logged in as root:
	export KUBECONFIG=/root/.kube/config
	rm -rf /root/.helm
	./helm init -c --debug

root@veeresh-spinnakerbuild:/home/ubuntu# helm ls --debug
[debug] Created tunnel using local port: '46624'
[debug] SERVER: "localhost:46624"

root@veeresh-spinnakerbuild:/home/ubuntu# helm version --debug
[debug] Created tunnel using local port: '44653'
[debug] SERVER: "localhost:44653"
Client: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}

2) Followed this link: https://hackernoon.com/the-missing-ci-cd-kubernetes-component-helm-package-manager-1fe002aac680 
   to install a sample hello-world app using helm. 
 
cd /home/ubuntu/hello-world
helm install . --debug

root@veeresh-spinnakerbuild:/home/ubuntu/hello-world# helm list --debug
[debug] Created tunnel using local port: '35190'

[debug] SERVER: "localhost:35190"

NAME            REVISION        UPDATED                         STATUS          CHART                   NAMESPACE
knobby-donkey   1               Mon Nov 13 21:12:42 2017        DEPLOYED        hello-world-1.0.0       kube-system

3)Logged into cbu-dev master0 node
cbu-dev-k8s-master0 core # ./kubectl get po --all-namespaces
NAMESPACE     NAME                                                              READY     STATUS    RESTARTS   AGE
kube-system   fluentd-23hk7                                                     1/1       Running   0          4d
kube-system   fluentd-5t7rh                                                     1/1       Running   0          4d
kube-system   fluentd-jr22g                                                     1/1       Running   0          4d
kube-system   hello-world-2541921211-vfzxt                                      1/1       Running   0          1m
=============================================================

**Comment by veeresh1982** [comment]
NAMESPACE     NAME                                                              READY     STATUS    RESTARTS   AG
kube-system   tiller-deploy-2318886584-1km4j                                    1/1       Running   0          41m

**Comment by veeresh1982** [comment]
Tested @philchristensen solution. It works too and with this no need to update /etc/hosts file on the master side.

**Comment by rhefner1** [comment]
Just as another input to this: I was experiencing this issue intermittently when deploying. Whenever the context deadline error appeared, I could try again and usually by the second or third try it would work. We have a VPN directly into our cluster, so I tried adding the `--host` flag to `helm upgrade` and I haven't ever gotten the error since.

**Comment by sefm** [comment]
I'm seeing same issue `only` when running helm in alpine container.

Hi - I'm seeing `Error: context deadline exceeded` error when trying helm install . This is only happening when running installer/helm on alpine container . It runs fine from linux box or mac . I tried to install grpc and excipliiitly define `export HELM_HOST=127.0.0.1:44134` instead of localhost and kubeconfig . Passing --host not working as well . The version I'm using is v2.7 .


 ```Tiller (the Helm server-side component) has been installed into your Kubernetes Cluster.
Happy Helming!```
Also, tiller pod and service is running fine .

 ```[main] 2018/01/09 00:49:22 Starting Tiller v2.7.0 (tls=false)
[main] 2018/01/09 00:49:22 GRPC listening on :44134
[main] 2018/01/09 00:49:22 Probes listening on :44135
[main] 2018/01/09 00:49:22 Storage driver is ConfigMap
[main] 2018/01/09 00:49:22 Max history per release is 0```

Any suggestion ! @munnerz I saw you had same issue!

**Comment by sefm** [comment]
I resolved the above issue by setting NO_PROXY in alpine container. It seems because go libraries don't owner no_proxy . Example : `NO_PROXY=localhost,127.0.0.1,169.254.169.254,localaddress,.localdomain.com,.<company_domain>.com` .

**Comment by kaazoo** [comment]
@sefm Setting NO_PROXY environment variable in the shell of the Alpine Linux container doesn't work for me. helm still fails with the same error. 'kubectl get all' works on the other hand.

**Comment by TheOriginalAlex** [comment]
@bacongobbler: Ping me if you think #3238 could be the root of this issue.

**Comment by chris-mccoy** [comment]
I was running into this issue as well running Helm from Ubuntu 16.04LTS outside of a bare-metal cluster.  I'm running Calico for networking and am exporting the svc cluster IPs so I can reach those directly.  I wasn't seeing any kind of network connection created at all.  Turns out, I had to add a port to `HELM_HOST`, e.g. `export HELM_HOST=10.10.254.5:44134`.

Now I'm up and running.

```
$ helm version
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
```

This didn't work for me.

```
$ helm version --debug --host 10.10.254.5
[debug] SERVER: "10.10.254.5"

Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
[debug] context deadline exceeded
Error: cannot connect to Tiller
```

This works:

```
$ helm version --debug --host 10.10.254.5:44134
[debug] SERVER: "10.10.254.5:44134"

Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
```

**Comment by LSmith130** [comment]
Still seeing the original issue with v2.8.2 running kubernetes in docker-for-mac edge.
```
$ helm version
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}

$ helm get manifest curatrix-int-tests --debug
[debug] Created tunnel using local port: '54054'

[debug] SERVER: "127.0.0.1:54054"

Error: context deadline exceeded
```
Regular `helm get`, `helm get values`, and `helm get hooks` all work just fine.

Nothing exceptional in the tiller logs:
```
[main] 2018/03/17 15:52:02 Starting Tiller v2.8.2 (tls=false)
[main] 2018/03/17 15:52:02 GRPC listening on :44134
[main] 2018/03/17 15:52:02 Probes listening on :44135
[main] 2018/03/17 15:52:02 Storage driver is ConfigMap
[main] 2018/03/17 15:52:02 Max history per release is 0
```

**Comment by xiangpengzhao** [comment]
Facing this with 2.8.2 as well.

```
root@ubuntu:/home# helm get manifest vigilant-tapir
Error: context deadline exceeded
```
```
root@ubuntu:/home# helm version
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```

No related logs within tiller container.

cc @bacongobbler  Thanks!

**Comment by alexvicegrab** [comment]
Same issue here, with helm 2.8.2 both using a brew installation and "from script"

**Comment by bacongobbler** [comment]
https://github.com/kubernetes/helm/pull/3715 is the fix for this. Could one of you please try that branch and see if it works for you? Thanks!

**Comment by xiangpengzhao** [comment]
@bacongobbler awesome! The patch works for me!

```
root@ubuntu:/home/cloud/helmtmp# ./helm version
Client: &version.Version{SemVer:"v2.8+unreleased", GitCommit:"87c64e7987f348c0a99a4f6e12d6ec187723b7cc", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8+unreleased", GitCommit:"87c64e7987f348c0a99a4f6e12d6ec187723b7cc", GitTreeState:"clean"}
```

```
root@ubuntu:/home/cloud/helmtmp# ./helm install stable/linkerd
NAME:   existing-bison
LAST DEPLOYED: Tue Mar 20 11:15:34 2018
.......
```

```
root@ubuntu:/home/cloud/helmtmp# ./helm get manifest existing-bison

---
# Source: linkerd/templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
......
```

**Comment by edwardstudy** [comment]
Reproduce:
```
/scripts/helm_mac get manifest cf.20180507.130920 --debug
[debug] Created tunnel using local port: '58010'

[debug] SERVER: "127.0.0.1:58010"

Error: context deadline exceeded
IBMMasterMBP:bcf-deployer bjxzi$ ./scripts/helm_mac version --debug
[debug] Created tunnel using local port: '58046'

[debug] SERVER: "127.0.0.1:58046"

Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Kubernetes: &version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.11-2+fa6873d3e386d7", GitCommit:"fa6873d3e386d7ead42923b24aea3b76e74395a3", GitTreeState:"clean", BuildDate:"2018-04-17T08:10:40Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```

**Comment by edwardstudy** [comment]
@rabbitfang Hi, I upgraded helm but got same error:

```
bjxzi$ ./scripts/helm_mac get  manifest cf.20180516.143139 --debug
[debug] Created tunnel using local port: '49509'

[debug] SERVER: "127.0.0.1:49509"

Error: context deadline exceeded
bjxzi$ helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

**Comment by bacongobbler** [comment]
Is it possible ./scripts/helm_mac is using a different client? You call both that script and helm directly in that example.

**Comment by bacongobbler** [comment]
That makes sense then... As it's been mentioned a few times in this thread now, the Helm 2.8.2 client does **not** have this fix. You need to use the 2.9 client if you want to use `helm get manifest`. The fix was purely client-side.

**Comment by edwardstudy** [comment]
@bacongobbler Sorry, I missed that `get manifest` command was using v2.8.2.
