### ISSUE TITLE
Extremely High Risk of Password Leakage on Private Repositories

### ISSUE THREAD

**Issue by apeschel** [kubernetes/helm#3092]
At the moment, password management for private repositories is far too primitive, and causes the username and password to be exposed in far too many places. Every place the private repository URL is used, the username and password must also be included. This means the following places require a copy of the username and password:

On a client:

1. `requirements.yaml`
2. `requirements.lock`
3. helm repo list command shows username/password
4. `~/.helm/repository/repositories.yaml`

On a server:

1. htaccess file
2. `index.yaml`

Failure to place the username/password in the repository URL in any of these places will cause a failure.

Having the username/password duplicated in this many places, and especially if you're keeping the requirements files in a git repository, creates an extremely high risk of accidental password leakage. The only places where the username/password should be required are in `~/.helm/repository/repositories.yaml` and `htaccess`

**Comment by jascott1** [comment]
I agree the security situation needs improvement but since it is functioning "as designed" right now I labeled this issue as Feature.

**Comment by apeschel** [comment]
@jascott1 Makes sense to me.

**Comment by apeschel** [comment]
Helm has provided support for repository shorthand in `requirements.yaml`, which helps with this problem, but doesn't fully solve it.

EG, if you have a repository with the name "stable" you can use "@stable" in your requirements.yaml, rather than the full URL as previously required.

However, the other problem areas remain:

On a client:

* `helm repo list` command shows username/password

On a server:

* `index.yaml` requires username/password

**Comment by bacongobbler** [comment]
> helm repo list command shows username/password

See #3206 for that

**Comment by bacongobbler** [comment]
I think we can close this entire issue out with #3206 actually.

**Comment by apeschel** [comment]
@bacongobbler Just a couple of things of note

* This should probably be linked to #3206 and be closed when that PR is merged rather than just closed immediately.
* It's not clear if #3206 will fix the index.yaml problem.

**Comment by bacongobbler** [comment]
I believe that was fixed when relative path support was introduced in https://github.com/kubernetes/helm/pull/3065 in v2.7.1. Can you describe how you're generating your index.yaml files?

**Comment by bacongobbler** [comment]
closed via #3206

**Comment by ankushchadha** [comment]
#3206 doesn't fix the password leakage issue. What it results in is exposing username and password in plaintext as part of repositories.yaml file. This ticket looks similar to https://github.com/kubernetes/helm/issues/3102
