### ISSUE TITLE
default function treats boolean false as not defined, and applies default

### ISSUE THREAD

**Issue by Stono** [kubernetes/helm#3308]
values.yaml:
```
someKey: false
```

in template:
```
{{ default true .Values.someKey }}
```

I would expect this to return `false`, as `someKey` is defined, and its value is false, however it returns true.

**Comment by bacongobbler** [comment]
You have the arguments flipped in the wrong direction. It should be `{{ default .Values.somekey false }}`. `default` takes its first argument as the value to check if it exists, then defaults to the second argument if it's not defined.

**Comment by Stono** [comment]
@bacongobbler apologies, i noticed this too but it's still incorrect the other way....

values.yaml
<img width="276" alt="screen shot 2017-12-31 at 20 02 25" src="https://user-images.githubusercontent.com/1486729/34463963-71b57774-ee65-11e7-9285-fb02d9db4769.png">

template:
<img width="455" alt="screen shot 2017-12-31 at 20 02 07" src="https://user-images.githubusercontent.com/1486729/34463960-649c8852-ee65-11e7-94b6-67127cdce346.png">

You would expect that to be false however:

<img width="205" alt="screen shot 2017-12-31 at 20 01 47" src="https://user-images.githubusercontent.com/1486729/34463959-5c08a86a-ee65-11e7-89a7-4235ab531e00.png">

**Comment by bacongobbler** [comment]
Ah, I forgot that "empty value" is `false` when in reference to booleans, so I don't think you can use `default` in the way you want to.

https://github.com/Masterminds/sprig/blob/ecbec66c2936b6503e7c9e29123e343be03ac8eb/docs/defaults.md#default

It's probably better to use `{{ if $deployment.enabled }}{{ $deployment.enabled }}{{ else }}true{{ end }}` instead.

**Comment by Stono** [comment]
Ahh that clarifies, how annoying!  
Thanks dude.

**Comment by tw0517tw** [comment]
Hi @bacongobbler ,

What if I'd like to use this in a block `if` in my template? Something like:

```
{{- if (default $foo true) }}
someSetting: "bar"
{{- end }}
```

and I want the `someSetting` to not render only when `$foo` is explicitly set to `false`.

**Comment by max-tet** [comment]
This is still open, istn't it?
The workaround provided by @bacongobbler does not seem to work.
There must be some way to distinguish `null` from `false`? How else can you set a default to `true` and make it overridable by a `false` value?

**Comment by atombender** [comment]
This is the workaround I use:

```
{{ if or (not (hasKey . "enabled")) (eq (coalesce .enabled false) true) }}
...
{{ end }}
```

Obviously, if the dictionary you're checking is something like `$foo`:

```
{{ if or (not (hasKey $foo "enabled")) (eq (coalesce $foo.enabled false) true) }}
...
{{ end }}
```

The reason I'm using `coalesce` is because `eq .enabled true` fails (`error calling eq: invalid type for comparison`) with nil/null errors for some dastardly reason.

**Comment by marcinma** [comment]
Why this is closed? Issue still exists

**Comment by bacongobbler** [comment]
What issue are you seeing @marcinma? What's your recommendation for a fix?

**Comment by atombender** [comment]
> You have the arguments flipped in the wrong direction. It should be `{{ default .Values.somekey false }}`

That's [wrong](https://masterminds.github.io/sprig/defaults.html). `default` takes the default value as its first argument, and the value to be tested as the second. I use this all the time. Yes, the order is weird, but the OP is right.

There's a bug here and this needs to reopened.

**Comment by atombender** [comment]
The issue has been [reported in Sprig](https://github.com/Masterminds/sprig/issues/111).

**Comment by marcinma** [comment]
> What issue are you seeing @marcinma? What's your recommendation for a fix?

Lets start with obvious test:
```sh
$> cat values.yaml

bugExists: false

$> cat templates/bug.yaml

defaul result oposite: {{ default .Values.bugExists true }}
default result normal: {{ default  true .Values.bugExists }}
real value: {{ .Values.bugExists }}

$> helm template --output-dir=out .
wrote out/test/templates/bug.yaml

$> cat out/test/templates/bug.yaml
---
# Source: test/templates/bug.yaml
defaul result oposite: true
default result normal: true
real value: false

```
Although false is defined it is not used in any case.
At lest helm documentation should describe this behavior until fixed here:
https://github.com/helm/helm/blob/master/docs/chart_template_guide/functions_and_pipelines.md#using-the-default-function

Not sure how this can be fixed yet this bug shouldn't be closed.

**Comment by gabordk** [comment]
> What if I'd like to use this in a block `if` in my template? Something like:
> 
> ```
> {{- if (default $foo true) }}
> someSetting: "bar"
> {{- end }}
> ```
> 
> and I want the `someSetting` to not render only when `$foo` is explicitly set to `false`.

@tw0517tw Did you found any solution to this?

**Comment by tw0517tw** [comment]
@gabordk No I didn't find any.

**Comment by andyliuliming** [comment]
sad to see this does not work:
{{ $ba := and (.Values.global.oneBool) (default true .Values.global.anotherbool) }}

**Comment by mentos1386** [comment]
@bacongobbler If this is working as intended (that you cannot use `default` with booleans). Can it be added to documentation, as a warning? Or reopen the issue if it isn't working as intended.

**Comment by cjmaloof** [comment]
Similarly, an integer value of 0 is always replaced by the default.

**Comment by cosimps** [comment]
> Hi @bacongobbler ,
> 
> What if I'd like to use this in a block `if` in my template? Something like:
> 
> ```
> {{- if (default $foo true) }}
> someSetting: "bar"
> {{- end }}
> ```
> 
> and I want the `someSetting` to not render only when `$foo` is explicitly set to `false`.

@gabordk this is my workaround that I am using is a few templates:
```
{{ if or (.Values.enabled) (eq (.Values.enabled | toString) "<nil>") }}
someSetting: bar
{{- end }}
```
in action:
```
$> cat chart/values.yaml

enabled: true

$> helm template chart/

---
someSetting: bar
otherSetting: foo
```
```
$> cat chart/values.yaml

$> helm template chart/

---
someSetting: bar
otherSetting: foo
```
```
$> cat chart/values.yaml

enabled: false

$> helm template chart/

---
otherSetting: foo
```

**Comment by sshishov** [comment]
Hey guys, you can try to use this one solution, which we are using:
```
someKey: false
```
```
anotherKey: {{ hasKey .Values "someKey" | ternary .Values.someKey true }}
```

**Comment by schollii** [comment]
I use this: 
```
{{- if or .Values.myVar (not (hasKey .Values "myVar")) }}
...
{{- end }}
```
This basically says "render the block if the value is true, OR if the value is false because the key does not exist". 

I find this easier to understand than the ternary function and does not depend on the variable's value.

**Comment by pawamoy** [comment]
Thanks @schollii, worked for me. The documentation should definitely state that values that evaluate to false cannot be used with the `default` function, or the function should be changed to work similarly to Jinja2's `default` filter:

![image](https://user-images.githubusercontent.com/3999221/109489037-9ccfc300-7a86-11eb-80b5-d54d9e43dc1f.png)

**Comment by MeNsaaH** [comment]
```yaml
{{ if (eq (default "true" (.Values.myVar|toString|lower)) "true") }}
...
{{- end }}
```

Currently using this

**Comment by ryancastle** [comment]
```
{{- if ne "false" (.value | toString) }}
# Do something 
{{- end }}

**Comment by cdlliuy** [comment]
I am surprised that  I still see this bug in 2021...

The "if + default"  make me confused since it behaviors differently with different default value. 

with 
```
{{- if .Values.somekey| default false }}
<code block>
{{-end }}
```
and explicitly define "somekey: true" ,  then `<code-block>` will be executed as expected. 


But on the other hand, 
```
{{- if .Values.somekey| default true}}
<code block>
{{-end }}
```
and explicitly define "somekey: false" ,  then `<code-block>` is still be executed which is not expected at all.

I personally picked up the workaround provided by  @sshishov  in
https://github.com/helm/helm/issues/3308#issuecomment-701367019,  but I still wonder why helm works with `if/default` in such a confusing behavior as mentioned above.

**Comment by danielGz** [comment]
I can't believe this hasn't been reopened

**Comment by scollins33** [comment]
Yeah I just spent 4 hours trying to debug our cloud team's template code only to find this thread. So counter-intuitive.

**Comment by davinkevin** [comment]
Like all other, I vote to reopen this issue 😇 please.

**Comment by NBardelot** [comment]
This whole thread is unbelievable. 4 years... 👎

**Comment by gw0** [comment]
A new issue to update the docs for the `default` function probably needs to be opened. It should contain a warning and as a recommended workaround I suggest something generic:

```
## this is always true if $defaults.enableIngress is true:
{{- if (default $defaults.enableIngress .enableIngress) }}

## replacement that works as expected:
{{- if hasKey . "enableIngress" | ternary .enableIngress $defaults.enableIngress }}
```

**Comment by kcasas** [comment]
simplest workaround I've come up is this
```
list nil true | has .Values.vaultEnabled
```

**Comment by Lillecarl** [comment]
`{{if ((.Values.health).enabled)}}`

This works well for me, in case anyone still cares about this.

**Comment by prashant-shahi** [comment]
I had same issue with `"false"` and `"true"` i.e. Boolean as string being set in the pod ENVs.
`default` assumed the string to be boolean.

I solved it by using and explicit `quote` on top of `.Values.insecure` being a string `"false"` itself..
```
{{- define "app.isInsecure" -}}
{{- default "true" (.Values.insecure | quote) }}
{{- end }}
```

**Comment by whatthefrog** [comment]
> [kcasas](/kcasas)

In some cases it may be usefule to also add the `"true"` string to the checked list

`list nil true "true" | has .Values.vaultEnabled`

**Comment by joejulian** [comment]
> Hi @bacongobbler ,
> 
> What if I'd like to use this in a block `if` in my template? Something like:
> 
> ```
> {{- if (default $foo true) }}
> someSetting: "bar"
> {{- end }}
> ```
> 
> and I want the `someSetting` to not render only when `$foo` is explicitly set to `false`.

I do:
```
{{- if (dig "somekey" true .Values) }}
someSetting: bar
{{- end }}
```
Which looks in .Values for the key, "somekey". If it's there, it uses that value. If it's not, it uses (in the above example) true as the default.

**Comment by jbilliau-rcd** [comment]
> > Hi @bacongobbler ,
> > What if I'd like to use this in a block `if` in my template? Something like:
> > ```
> > {{- if (default $foo true) }}
> > someSetting: "bar"
> > {{- end }}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and I want the `someSetting` to not render only when `$foo` is explicitly set to `false`.
> 
> @gabordk and anyone else that my encounter this issue, this is my workaround that I am using is a few templates:
> 
> ```
> {{- if or (.Values.enabled) (eq (.Values.enabled | toString) "<nil>") }}
> someSetting: bar
> {{- end }}
> ```
> 
> in action:
> 
> ```
> $> cat chart/values.yaml
> 
> enabled: true
> 
> $> helm template chart/
> 
> ---
> someSetting: bar
> otherSetting: foo
> ```
> 
> ```
> $> cat chart/values.yaml
> 
> $> helm template chart/
> 
> ---
> someSetting: bar
> otherSetting: foo
> ```
> 
> ```
> $> cat chart/values.yaml
> 
> enabled: false
> 
> $> helm template chart/
> 
> ---
> otherSetting: foo
> ```

For anyone stumbling here from doing a google search on this issue, it is indeed still an issue but the real hero is @cosimps  whose workaround works beautifully. Much appreciated!

**Comment by DrewDevereux** [comment]
I know there are already plenty of workarounds in this thread, but I really love this one. Simply replace
```
{{ $deployment.enabled | default true }}
```
with
```
{{not (not $deployment.enabled | default false)}}
```

**Comment by dicky-yuen** [comment]
> `{{if ((.Values.health).enabled)}}`
> 
> This works well for me, in case anyone still cares about this.

It works. But can you explain why it works?

**Comment by Mo0rBy** [comment]
How is this not re-opened or fixed? This is a really helpful thread with some workarounds, but we shouldn't need it. This functionality with `default` and Booleans seems really simple and should work straight away

**Comment by Mo0rBy** [comment]
I'm going to put this solution to my problem here in case it helps anyone:

I wanted to render part of a template (a deployment label) by default unless the values.yaml explicitly stated that a value was false:

```
      labels:
        {{- if ne false ((.Values.security).istio).enabled }}
        sidecar.istio.io/inject: "true"
        {{- end }}
```

Here is the explanation of using the parenthesis on my evaluated value > https://stackoverflow.com/questions/59795596/how-to-make-nested-variables-optional-in-helm/68807258#68807258

And I am simply use a "not equals" which fits the logic very nicely. The users of my chart will have to explicitly state the specific value as `false` in order to not include this label in the deployment.

**Comment by vincentor** [comment]
five years later and i fall into the same hole now, this issue should be fixed

**Comment by Cajga** [comment]
Also run into this and spent an hour debugging a complex helm chart.
I can accept the "This is how default works so get used to it." answer but please at least it should be mentioned in the documentation.

**Comment by glebsts** [comment]
Almost six years and it is still an issue. I want to explicitly change default-`true` in subchart in my values, and I cannot use `false`.

**Comment by tgolly** [comment]
What I'm trying to do is:  if my `enabled` boolean is not defined, have it default to `true` (which I realise is unusual but I have a use case for it).

So:

* enabled == true             -> **true**
* enabled == false           -> **false**
* enabled "not defined" -> **true**

It thought either of these would work:

```
{{- if .enabled | default true }}
{{- if default true .enabled }}
```

...but they don't.  

After a lot of trial and error, this is the simplest workaround I could find:

```{{- if ne (toString .enabled) "false" }}```

This works because "toString" on an undefined boolean returns `<nil>`.

But still, having an undefined boolean [always return `false`](https://docs.helm.sh/docs/chart_template_guide/function_list/#default) instead of `not defined` means you cannot use the "default" function to set the default for a boolean.  It can only ever default to false.

Please re-open this issue, until the "default" function can be used with boolean values without these workarounds.

**Comment by cesium147** [comment]
I not found simple way to resolve case with set False when default value is True. 
But share my working version with next conditions:
- flag has value > value
- flag == true > true
- flag == false > false
- flag is empty > true
- flag is absent > true 

**template.yaml**
```yaml
---
flag1: {{ .Values.flag1 | default (eq (toString .Values.flag1) "<nil>" | ternary true false) }}
flag2: {{ .Values.flag2 | default (eq (toString .Values.flag2) "<nil>" | ternary true false) }}
flag3: {{ .Values.flag3 | default (eq (toString .Values.flag3) "<nil>" | ternary true false) }}
flag4: {{ .Values.flag4 | default (eq (toString .Values.flag4) "<nil>" | ternary true false) }}
flag5: {{ .Values.flag5 | default (eq (toString .Values.flag5) "<nil>" | ternary true false) }}
```
**values.yaml**
```yaml
---
flag1: test
flag2: true
flag3: false
flag4: 
# flag5:
```
**output**
```yaml
---
flag1: test
flag2: true
flag3: false
flag4: true
flag5: true
```

**Comment by michelefa1988** [comment]
> What I'm trying to do is: if my `enabled` boolean is not defined, have it default to `true` (which I realise is unusual but I have a use case for it).
> 
> So:
> 
> * enabled == true             -> **true**
> * enabled == false           -> **false**
> * enabled "not defined" -> **true**
> 
> It thought either of these would work:
> 
> ```
> {{- if .enabled | default true }}
> {{- if default true .enabled }}
> ```
> 
> ...but they don't.
> 
> After a lot of trial and error, this is the simplest workaround I could find:
> 
> `{{- if ne (toString .enabled) "false" }}`
> 
> This works because "toString" on an undefined boolean returns `<nil>`.
> 
> But still, having an undefined boolean [always return `false`](https://docs.helm.sh/docs/chart_template_guide/function_list/#default) instead of `not defined` means you cannot use the "default" function to set the default for a boolean. It can only ever default to false.
> 
> Please re-open this issue, until the "default" function can be used with boolean values without these workarounds.

@tgolly  I have exactly your used case and I have not been able to workaround it. Did you manage to find a workaround at the end?

**Comment by tgolly** [comment]
> @tgolly I have exactly your used case and I have not been able to workaround it. Did you manage to find a workaround at the end?

@michelefa1988   No.    😢 

This issue really needs to be re-opened.

**Comment by detro** [comment]
The issue has to be reopened. The root of the issue boils down to the coalescing of `absence of boolean` to `false`.
Given that making a change to the `default` function would break an entire ecosystem (and have probably a swarm of ppl descend on Helm with pitchforks), my advice is to go for an additional function. A `default_boolean` that offers a way to control the coalescence better.

**Comment by pawamoy** [comment]
I suspect some comments are downvoted because they either don't bring anything to the discussion, or are not respectful. I've just unsubscribed :slightly_smiling_face: Good luck everybody!

**Comment by tgolly** [comment]
I think you are right @pawamoy .

**Comment by FahadBSyed** [comment]
We just hit this too, kind of silly that this hasn't been fixed yet

**Comment by pderrierw** [comment]
@michelefa1988 @tgolly 
I found this workaround that does the expected (evaluate as true when .Element.enabled is either true either unset)
NB, applying toString directly to .Element.enabled won't work, thus the default in between 

`    {{- if ne (toString (default "false" (.Element).enabled)) "false" -}}
`
Hope it helps
