### ISSUE TITLE
Upgrades fails with: grpc: received message larger than max

### ISSUE THREAD

**Issue by balboah** [kubernetes/helm#3512]
After adding more grafana dashboards that are populated via configmap from files:
```
{{ (.Files.Glob "assets/generated/*.json").AsConfig | indent 2 }}
```
And running upgrade: `helm upgrade --install -f values-staging.yaml dev .`
I'm now receiving:
`Error: UPGRADE FAILED: grpc: received message larger than max (4290838 vs. 4194304)`

After deleting some of the larger dashboard files it works again. This might be related to https://github.com/kubernetes/helm/issues/3322

---
```
Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
```

**Comment by balboah** [comment]
While poking around in the code it looks like the size limit has already been attempted to be bumped: https://github.com/kubernetes/helm/blob/master/pkg/tiller/server.go#L34

but still the default limit is what is printed in the error

**Comment by koenfaro90** [comment]
Fixed by https://github.com/kubernetes/helm/pull/3528

**Comment by mausch** [comment]
I'm getting this on v2.8.1 and v2.7.2

**Comment by raul-gherman** [comment]
hi guys,

Received message larger than max (75309533 vs. 4194304)

this is still present in c# implementation, latest code version

best regards,

Raul

**Comment by balboah** [comment]
@raul-gherman which c# implementation?

**Comment by thenano** [comment]
What is the proposed solution if a chart exceeds the 20Mb limit? I've reached that limit now using stable/prometheus with a bunch of alert rules configured.

**Comment by rrajadevops** [comment]
@balboah  @bacongobbler @koenfaro90 @mausch I am also experiencing same issue,

**helm version**
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

helm upgrade name charts --set fe_image.tag=test0.0.234
Error: UPGRADE FAILED: grpc: received message larger than max (475664632 vs. 20971520)

Kindly suggest what is the best way to fix this issue.

**Comment by bacongobbler** [comment]
Check if there's any artifacts in your chart directory that shouldn't be there. 400MB seems like an abnormally large chart.

**Comment by bacongobbler** [comment]
@thenano unfortunately there's no proposed solutions in helm once you're over the 20mb limit. I know there was a proposal out there for streaming the upload API but I don't think anyone from the community has started working on that.

**Comment by rwestergren** [comment]
> I'm getting this on v2.8.1 and v2.7.2 and v2.6.2 and v2.5.1. Couldn't go further back, Tiller v2.4.1 won't deploy on k8s 1.8.
> 
> EDIT: this was caused by having an undesired large file in my chart directory. #3563

Large file in chart directory was also the source for me.

**Comment by vishrantgupta** [comment]
I had a really large (unnecessary log) file in my project. Upon removing, that fixed the issue.

**Comment by parmarnikunj** [comment]
if you have kept your chart.yaml and templates in the same directory as in source directory, this happens. So better structure is to put all helm related stuff in a separate directory. 

e.g. src -> helm-> Chart.yaml and templates -> *.yaml

**Comment by amit-k-yadav** [comment]
> I'm getting this on v2.8.1 and v2.7.2 and v2.6.2 and v2.5.1. Couldn't go further back, Tiller v2.4.1 won't deploy on k8s 1.8.
> 
> EDIT: this was caused by having an undesired large file in my chart directory. #3563

You are godsend!!! 🙏

**Comment by CVirus** [comment]
I found a large forgotten binary inside the directory I was trying to install the chart from.

**Comment by kjozsa** [comment]
What worked for me is to put any unrelated stuff in the helm chart's directory into `.helmignore`. Now I don't get this error..
