### ISSUE TITLE
extend value range for versions

### ISSUE THREAD

**Issue by remmeier** [kubernetes/helm#3776]
`helm version`: 2.8.2

We make use of a CI/CD chain where versions are derived from the git commit timestamp. A version then may look like 0.1.20180328112652. As such every build gets a new version and may later gets promoted to a release.

Helm should support such versioning schemes. Currently this results in an Integer parsing error, saying that the value is out of range.

As a workaround I managed to get it working with  0.20180328.112652, but such a version scheme is rather undesired.

**Comment by bacongobbler** [comment]
fixed with the new `--set-string` feature flag being introduced in Helm 2.9. See https://github.com/kubernetes/helm/pull/3599 for more info

**Comment by remmeier** [comment]
I think the issue still persists. e.g. helm package  with --version ... will not accept longs.

**Comment by remmeier** [comment]
@bacongobbler this is still open, could the issue be reopened?
