### ISSUE TITLE
can't connect to 127.0.0.1:8080

### ISSUE THREAD

**Issue by casualjim** [kubernetes/helm#3986]
I can't get helm to work on a new minikube install

```
minikube start --cpus 4 --memory 12288 --vm-driver kvm2
minikube addons enable heapser
minikube addons enable ingress
minikube addons enable freshpod
minikube addons enable registry-creds
helm init
```

```shellsession
$ helm install --name oc --set server.service.type=NodePort --set rbac.create=false stable/prometheus
Error: Get http://localhost:8080/version: dial tcp 127.0.0.1:8080: connect: connection refused
```

```shellsession
$ helm list
Error: Get http://localhost:8080/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%!D(MISSING)TILLER: dial tcp 127.0.0.1:8080: connect: connection refused
```

```shellsession
$ helm reset
Error: Get http://localhost:8080/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%!D(MISSING)TILLER: dial tcp 127.0.0.1:8080: connect: connection refused
```

Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

minikube: 0.26.1

**Comment by djzager** [comment]
Yeah. Running into this issue in our Travis builds [here](https://travis-ci.org/openshift/ansible-service-broker/jobs/372149484#L2466).

On an older version of helm (locally) I do not see this issue.

```
# minikube start
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.
Loading cached images from config file.

# helm init
$HELM_HOME has been configured at /home/dzager/.helm.

Tiller (the Helm server-side component) has been installed into your Kubernetes Cluster.
Happy Helming!

#  linux git:(master) ✗ kubectl create clusterrolebinding tiller-cluster-admin --clusterrole=cluster-admin --serviceaccount=kube-system:default
clusterrolebinding "tiller-cluster-admin" created

#  linux git:(master) ✗ helm install svc-cat/catalog --name service --namespace=kube-service-catalog
NAME:   service
LAST DEPLOYED: Fri Apr 27 14:21:58 2018
NAMESPACE: kube-service-catalog
STATUS: DEPLOYED

RESOURCES:
...
```

Version related info:

```
# minikube version
minikube version: v0.26.1

# helm version
Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}

#  kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-12T16:29:47Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by djzager** [comment]
This issue is similar to #3985

**Comment by bacongobbler** [comment]
closing as a duplicate of #3985.

**Comment by bacongobbler** [comment]
FYI if you would be so kind as to test #3990, that would be appreciated. Seems like there was a regression in 2.9.

**Comment by bacongobbler** [comment]
alternative PR: #3991

**Comment by casualjim** [comment]
I can confirm that #3991 fixes the issue

**Comment by bacongobbler** [comment]
This has been fixed in helm v2.9.1, which is available here: https://github.com/kubernetes/helm/releases/v2.9.1

Thanks everyone!

**Comment by kundanatre** [comment]
Still it is reproducible in 2.9.1
```
 helm ls
Error: Get http://localhost:8080/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%!D(MISSING)TILLER: dial tcp 127.0.0.1:8080: connect: connection refused
```
helm version 

```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

**Comment by roobert** [comment]
@kundantre: you will still have this issue if you upgraded from 2.9.0 to 2.9.1, try removing tiller from the cluster first.

**Comment by kundanatre** [comment]
@roobert  Thanks, I have not upgraded tiller or helm; this is what I'm getting it via jx install.
Also i have deleted tiller multiple times.

**Comment by bacongobbler** [comment]
If you are still hitting this error on 2.9.1, it is very likely that RBAC is involved and you'll need to follow https://docs.helm.sh/using_helm/#role-based-access-control to fix that

**Comment by quantum-fusion** [comment]
Still seeing the same bug in v2.13.0.

helm ls
Error: Get http://localhost:8080/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: dial tcp 127.0.0.1:8080: connect: connection refused
Windows10-Pro:~ quantum-fusion$ helm version
Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Error: Get http://localhost:8080/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: dial tcp 127.0.0.1:8080: connect: connection refused
Windows10-Pro:~ quantum-fusion$

**Comment by quantum-fusion** [comment]
@bacongobbler Can you comment on the errors with tiller and helm with connection refused?

**Comment by quantum-fusion** [comment]
@bacongobbler Here is a good test case.  (https://daemonza.github.io/2017/02/20/using-helm-to-deploy-to-kubernetes/ ).  We are having the Microsoft OpenHack conference, and are wondering what version of Helm is installed on Azure.

**Comment by quantum-fusion** [comment]
@bacongobbler I executed a different test on MAC (https://docs.bitnami.com/kubernetes/how-to/create-your-first-helm-chart/).

613  helm install --dry-run --debug ./mychart
  614  helm install --dry-run --debug ./mychart --set service.internalPort=8080
  615  helm install --name example ./mychart --set service.type=NodePort
  616  export NODE_PORT=$(kubectl get --namespace default -o jsonpath="{.spec.ports[0].nodePort}" services example-mychart)
  617  export NODE_IP=$(kubectl get nodes --namespace default -o jsonpath="{.items[0].status.addresses[0].address}")
  618  echo http://$NODE_IP:$NODE_PORT
  619  helm ls
  620  history
MacBook-Pro:~/Desktop quantum-fusion$ helm ls
NAME   	REVISION	UPDATED                 	STATUS  	CHART        	NAMESPACE
example	1       	Tue Mar 19 20:03:48 2019	DEPLOYED	mychart-0.1.0	default  
MacBook-Pro:~/Desktop quantum-fusion$ helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

It appears that on MAC with Helm v2.9.1 the test was successful, however the previous test on Windows10 with Ubuntu with Helm version 2.13.0 failed.

**Comment by PaulGobin** [comment]
I am also running into this issue: Ubuntu
steps:
$ curl -LO https://git.io/get_helm.sh
$ chmod 700 get_helm.sh
$ ./get_helm.sh

helm version:
:~$ helm version
Client: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
Error: Get http://localhost:8080/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: dial tcp [::1]:8080: connect: connection refused

**Comment by vadasambar** [comment]
What worked for me was deleting the tiller deployment in kube-system namespace 

```sh
kubectl delete deployment tiller-deploy -n kube-system
``` 

And run helm init to initialize the tiller deployment again

```sh

helm init
```

helm init might take a couple of seconds.

**Comment by jeevavenkataraman** [comment]
> What worked for me was deleting the tiller deployment in kube-system namespace
> 
> ```shell
> kubectl delete deployment tiller-deploy -n kube-system
> ```
> 
> And run helm init to initialize the tiller deployment again
> 
> ```shell
> helm init
> ```
> 
> helm init might take a couple of seconds.
Got the same issue after restarting Minicube an doing the above works!
